/*! Generated by scripts/build-version.js — do not edit.
    Content hash of the files GitHub Pages serves. Compare against the live
    site with `npm run deploy:check`. */
const BUILD = { id: "487f1417" };
