"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

/* Order is the cascade. app.css is a plain concatenation in this sequence, so
   moving an entry here changes which rule wins — the numbers leave room to
   insert without renumbering, and nothing else enforces it. */
const STYLE_SOURCES = [
  "src/styles/00-base.css",
  "src/styles/10-nav.css",
  "src/styles/20-shell.css",
  "src/styles/30-data.css",
  "src/styles/40-control.css",
  "src/styles/50-preview.css",
  "src/styles/60-timesheet.css",
  "src/styles/65-controls.css",
  "src/styles/70-home.css",
  "src/styles/80-mobile.css",
  "src/styles/85-accessibility.css",
  "src/styles/90-range-slider.css",
  "src/styles/92-pipe-wrap.css",
  "src/styles/94-utilities.css",
  "src/styles/96-detail-layout.css",
  "src/styles/98-layout-svg.css",
  // Last on purpose: it overrides for print without raising specificity.
  "src/styles/99-print.css"
];
const OUT_FILE = "app.css";

const BANNER = "/*! Generated by scripts/build-styles.js from src/styles/*.css — do not edit.\n" +
  "    Comments are stripped on the way out; every rule's reasoning lives in the source. */\n";

/* A tokenizer rather than a regex, because a comment opener is only an opener
   outside a string: a `content` value holding one is legal CSS, and a naive
   replace eats the rest of the file from there. Strings are copied through
   verbatim, and CSS ends an unterminated one at the newline, so a stray quote
   cannot swallow the sheet either. A bang-comment is kept, which is how the
   banner survives its own pass. */
function stripComments(css) {
  let out = "";
  let i = 0;
  while (i < css.length) {
    const c = css[i];

    if (c === '"' || c === "'") {
      let j = i + 1;
      while (j < css.length) {
        if (css[j] === "\\") { j += 2; continue; }
        if (css[j] === c) { j += 1; break; }
        if (css[j] === "\n") break;
        j += 1;
      }
      out += css.slice(i, j);
      i = j;
      continue;
    }

    if (c === "/" && css[i + 1] === "*") {
      const keep = css[i + 2] === "!";
      const end = css.indexOf("*/", i + 2);
      const stop = end === -1 ? css.length : end + 2;
      if (keep) out += css.slice(i, stop);
      i = stop;
      continue;
    }

    out += c;
    i += 1;
  }
  return out;
}

/* What the stripper leaves behind: the indentation that led into a comment,
   and the blank lines around it. Runs of them collapse to one, so the output
   still has a rule per block rather than a long gap where a section note used
   to be. Not a minifier — the rules keep their own formatting, so app.css stays
   readable in devtools and a diff of it stays legible. */
function tidy(css) {
  return css
    .split("\n")
    .map(line => line.replace(/\s+$/, ""))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/^\n+/, "");
}

function buildStyles() {
  const css = STYLE_SOURCES.map(relPath => {
    const absPath = path.join(ROOT, relPath);
    return fs.readFileSync(absPath, "utf8");
  }).join("");

  fs.writeFileSync(path.join(ROOT, OUT_FILE), BANNER + tidy(stripComments(css)), "utf8");
}

if (require.main === module) {
  try {
    buildStyles();
    process.stdout.write("Built app.css\n");
  } catch (err) {
    process.stderr.write(`Style build failed: ${err.message}\n`);
    process.exit(1);
  }
}

module.exports = {
  buildStyles,
  stripComments,
  tidy,
  STYLE_SOURCES
};
