"use strict";

// Stamps the deploy with a content hash of the files GitHub Pages actually
// serves, so "is the latest online?" is answered by comparing bytes rather than
// by trusting a clock.
//
// Why a hash and not a build timestamp or a commit SHA: githooks/pre-push
// rebuilds and then refuses the push if any committed build output moved. A
// clock reading changes on every build, so that diff would never be clean
// again. `git rev-parse HEAD` is worse than it looks for the same reason — at
// pre-commit time HEAD is still the *parent* commit, so the stamp would ship one
// commit behind, and it would resolve differently at pre-push and re-dirty the
// diff. A hash of the output is stable for a given source tree, which is exactly
// the property the hooks are built on.
//
// Must run last in the build chain: it reads what the other three wrote.

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT_FILE = "version.js";

// Everything a visitor loads that this repo owns — which is not the same set as
// "everything the build generates". index.html loads four hand-written classic
// scripts before the bundle, and they are the app as much as it is: config.js
// carries the default sheet, the page registry and the icon map; simulation.js
// is the layout maths every page draws from; themes.js decides what the app
// looks like before React renders. Change any of them and every visitor gets a
// different app, while a hash of the generated files alone would swear nothing
// had moved and deploy:check would report the deploy as already live — the one
// answer it exists to give, given wrong.
//
// version.js itself is deliberately absent: hashing the file being written is
// circular, and nothing downstream of it needs to be covered.
//
// The manifest and its icons are here for the same reason index.html is: a
// visitor loads them and this repo owns them. The manifest is fetched on every
// page load; the icons only when somebody installs, but a deploy that changed
// the installed app's identity and reported itself already-live would be the
// same wrong answer. They are not regenerated by `npm run build` — make-icon.js
// is run by hand — so they cannot re-dirty the diff on their own.
const HASHED_FILES = [
  "index.html",
  "config.js",
  "simulation.js",
  "themes.js",
  "components.js",
  "app.css",
  "manifest.webmanifest",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512.png",
  "vendor/fontawesome.subset.css",
  "vendor/fa-solid-900.subset.woff2"
];

/** Content hash of the served tree. Byte-for-byte, so binaries count too. */
function buildId() {
  const hash = crypto.createHash("sha256");
  for (const rel of HASHED_FILES) {
    // The path goes in as well as the bytes: without it, two files swapping
    // contents would hash the same.
    hash.update(rel);
    hash.update(fs.readFileSync(path.join(ROOT, rel)));
  }
  return hash.digest("hex").slice(0, 8);
}

function render(id) {
  return `/*! Generated by scripts/build-version.js — do not edit.
    Content hash of the files GitHub Pages serves. Compare against the live
    site with \`npm run deploy:check\`. */
const BUILD = { id: ${JSON.stringify(id)} };
`;
}

function buildVersion() {
  const id = buildId();
  fs.writeFileSync(path.join(ROOT, OUT_FILE), render(id), "utf8");
  return id;
}

if (require.main === module) {
  try {
    process.stdout.write(`Built version.js — ${buildVersion()}\n`);
  } catch (err) {
    process.stderr.write(`Version build failed: ${err.message}\n`);
    process.exit(1);
  }
}

module.exports = { buildVersion, buildId, render, HASHED_FILES, OUT_FILE };
